### ISSUE TITLE
Ceramic hive cannot be picked up

### ISSUE THREAD

**Issue by tincancrab** [VinterNacht/FromGoldenCombs#15]
After firing in pit kiln, tried right clicking and hive became loose item, but unable to pick up into inventory.  Fired another, tried shift clicking, and had same result.

Will try turning off other mods to see if this rules out anything later.

**Comment by VinterNacht** [comment]
TinCanCrab -> You must have an empty bag slot to pick up the majority of the blocks from FGC.
