### ISSUE TITLE
Beeswax patch overwrites vanilla/modded attributes already present on Beeswax

### ISSUE THREAD

**Issue by TaskaRaine** [VinterNacht/FromGoldenCombs#4]
Uuuh we've got a small compatibility issue between our two mods, Golden Combs and Ancient Tools. We're both adding attributes to the beeswax but, instead of adding new attributes, we're both completely overwriting each other(and vanilla shelf display attributes too). I'll have it fixed up on my end with the next release of Ancient Tools.

I went ahead and recreated patches for your mod that'll let both mods work together, and allow beeswax to show up on shelves again too. This would be the beeswax patch in the game folder:

[
  {
    "op": "add",
    "path": "/attributes/barrelMoveToLiquidSlot",
    "value": true,
    "file": "itemtypes/resource/beeswax.json"
  },
  {
    "op": "add",
    "path": "/attributes/inContainerTexture",
    "value": {
        "base": "block/beehive/beeswax"
    },
    "file": "itemtypes/resource/beeswax.json"
  },
]

**Comment by VinterNacht** [comment]
I believe we addressed this, yes?

**Comment by TaskaRaine** [comment]
I think you'd mentioned that the solution above wasn't working for you o.o

**Comment by VinterNacht** [comment]
I believe this situation is corrected now.
