### ISSUE TITLE
Have broken 3 Ceramic hives and can't pick them up after firing them

### ISSUE THREAD

**Issue by Xenoprophet-Nail** [VinterNacht/FromGoldenCombs#7]
After firing several ceramic hives in my pit kilns I have noticed I can't pick them up off the ground with a right click, or from breaking them. Have I done something wrong? Is there an issue or process I have ignored? It's bad because we have the one natural hive, and I was able to craft the top half fine.. 

I find it strange that that has happened to all of us 3 times.

**Comment by VinterNacht** [comment]
Do you have an open bag slot? They can only be carried in backpack slots.

**Comment by Xenoprophet-Nail** [comment]
Yup, that did it.. Senility on my part, been a while since I handled bees in Vintage Story. When you told me that everything clicked lol.. Disregard my issue

**Comment by VinterNacht** [comment]
It's alright, I kinda went 'round the bend with using that 'bag slot' mechanic in this. I really enjoy the fact that the various parts have to be stored outside of a chest or other storage solution.
