### ISSUE TITLE
Cant attach honey pot to brood pot

### ISSUE THREAD

**Issue by Segwegler** [VinterNacht/FromGoldenCombs#7]
When I attempt to place an empty honey pot on a brood pot it does not attach. It is placed just like it is placed on the ground. This happens with right click and Shift right click
![honeypot](https://user-images.githubusercontent.com/39866468/152665133-e0751fb5-76ff-4fe8-b2c8-ea0e08d82018.png)

**Comment by Segwegler** [comment]
mod version 1.3.6-rc.4

**Comment by Segwegler** [comment]
Ive been looking through the source to try and learn about mods,
I saw this line change from rc 3 to rc4 in the BECeramicBroodPot.cs file
`else if (slot.Itemstack.Collectible.FirstCodePart() != "hivetop" && TryPut(slot) )`
would that make it ignore the hive top as an intractable object?

**Comment by VinterNacht** [comment]
Resolved in upcoming release.
